from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QWidget

class Ui_chat(QMainWindow):
    def setupUi(self, chat):
        chat.setObjectName("chat")
        chat.resize(466, 336)
        chat.setFixedSize(466, 336)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(chat.sizePolicy().hasHeightForWidth())
        chat.setSizePolicy(sizePolicy)
        self.serverpick = QtWidgets.QComboBox(parent=chat)
        self.serverpick.setGeometry(QtCore.QRect(10, 310, 111, 20))
        self.serverpick.setCurrentText("")
        self.serverpick.setObjectName("serverpick")
        self.label = QtWidgets.QLabel(parent=chat)
        self.label.setGeometry(QtCore.QRect(10, 280, 111, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.nicklabel = QtWidgets.QLabel(parent=chat)
        self.nicklabel.setGeometry(QtCore.QRect(130, 280, 331, 21))
        self.nicklabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.nicklabel.setObjectName("nicklabel")
        self.send = QtWidgets.QPushButton(parent=chat)
        self.send.setGeometry(QtCore.QRect(440, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send.setFont(font)
        self.send.setObjectName("send")
        self.message = QtWidgets.QLineEdit(parent=chat)
        self.message.setGeometry(QtCore.QRect(0, 240, 411, 31))
        self.message.setObjectName("message")
        self.signout = QtWidgets.QPushButton(parent=chat)
        self.signout.setGeometry(QtCore.QRect(130, 310, 75, 23))
        self.signout.setObjectName("signout")
        self.update = QtWidgets.QPushButton(parent=chat)
        self.update.setGeometry(QtCore.QRect(410, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setIconSize(QtCore.QSize(16, 16))
        self.update.setObjectName("update")
        self.avatar = QtWidgets.QPushButton(parent=chat)
        self.avatar.setGeometry(QtCore.QRect(380, 310, 75, 23))
        self.avatar.setObjectName("avatar")
        self.chatbox = QtWidgets.QListWidget(parent=chat)
        self.chatbox.setGeometry(QtCore.QRect(0, 0, 471, 241))
        self.chatbox.setObjectName("chatbox")

        self.retranslateUi(chat)
        QtCore.QMetaObject.connectSlotsByName(chat)

    def retranslateUi(self, chat):
        _translate = QtCore.QCoreApplication.translate
        chat.setWindowTitle(_translate("chat", "Чат"))
        self.label.setText(_translate("chat", "Выбор сервера"))
        self.nicklabel.setText(_translate("chat", "Добро пожаловать ...!"))
        self.send.setText(_translate("chat", "↵"))
        self.update.setText(_translate("chat", "🗘"))
        self.signout.setText(_translate("chat", "Выйти"))
        self.avatar.setText(_translate("chat", "Аватар"))

