from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow


class Ui_regform(QMainWindow):
    def setupUi(self, regform):
        regform.setObjectName("regform")
        regform.resize(580, 345)
        regform.setFixedSize(580, 345)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=regform)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 30, 451, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nickname = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.nickname.setObjectName("nickname")
        self.verticalLayout.addWidget(self.nickname)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.passwd = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.passwd.setObjectName("passwd")
        self.verticalLayout.addWidget(self.passwd)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=regform)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 170, 361, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.signin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.signin.setObjectName("signin")
        self.verticalLayout_2.addWidget(self.signin)
        self.regist = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.regist.setObjectName("regist")
        self.verticalLayout_2.addWidget(self.regist)
        self.res = QtWidgets.QLabel(parent=regform)
        self.res.setGeometry(QtCore.QRect(80, 280, 361, 31))
        self.res.setText("")
        self.res.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.res.setObjectName("res")
        self.securetype = QtWidgets.QCheckBox(parent=regform)
        self.securetype.setGeometry(QtCore.QRect(480, 110, 91, 17))
        self.securetype.setObjectName("securetype")
        self.doyoremember21stnight = QtWidgets.QCheckBox(parent=regform)
        self.doyoremember21stnight.setGeometry(QtCore.QRect(460, 200, 91, 17))
        self.doyoremember21stnight.setObjectName("doyoremember21stnight")

        self.retranslateUi(regform)
        QtCore.QMetaObject.connectSlotsByName(regform)

    def retranslateUi(self, regform):
        _translate = QtCore.QCoreApplication.translate
        regform.setWindowTitle(_translate("regform", "Регистрация"))
        self.label.setText(_translate("regform", "Логин"))
        self.label_2.setText(_translate("regform", "Пароль"))
        self.signin.setText(_translate("regform", "Войти"))
        self.regist.setText(_translate("regform", "Зарегестрироваться"))
        self.securetype.setText(_translate("regform", "Показать"))
        self.doyoremember21stnight.setText(_translate("regform", "Запомнить"))
